Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: blah
      DefinitionBody:
        swagger: "2.0"
        info:
          version: 2016-03-31T18:25:32Z
          title: blahblah
        basePath: blah
        schemes:
          - https
        paths:
          /hello:
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
                responses: {}
        definitions:
          Empty:
            type: object
    Metadata:
      aws:cdk:path: ServerlessStack/HelloWorldApi
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://deans-spike/hello-world.zip
      Handler: index.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /hello
            RestApiId:
              Ref: HelloWorldApi
          Type: Api
    Metadata:
      aws:cdk:path: ServerlessStack/HelloWorldFunction
  helloWorlFnPerm:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: HelloWorldFunction
      Principal: apigateway.amazonaws.com
    Metadata:
      aws:cdk:path: ServerlessStack/helloWorlFnPerm
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.3.0,@aws-cdk/assets=1.3.0,@aws-cdk/aws-apigateway=1.3.0,@aws-cdk/aws-applicationautoscaling=1.3.0,@aws-cdk/aws-autoscaling-common=1.3.0,@aws-cdk/aws-cloudwatch=1.3.0,@aws-cdk/aws-dynamodb=1.3.0,@aws-cdk/aws-ec2=1.3.0,@aws-cdk/aws-events=1.3.0,@aws-cdk/aws-iam=1.3.0,@aws-cdk/aws-kms=1.3.0,@aws-cdk/aws-lambda=1.3.0,@aws-cdk/aws-lambda-event-sources=1.3.0,@aws-cdk/aws-s3=1.3.0,@aws-cdk/aws-s3-assets=1.3.0,@aws-cdk/aws-s3-notifications=1.3.0,@aws-cdk/aws-sam=1.3.0,@aws-cdk/aws-sns=1.3.0,@aws-cdk/aws-sns-subscriptions=1.3.0,@aws-cdk/aws-sqs=1.3.0,@aws-cdk/aws-ssm=1.3.0,@aws-cdk/core=1.3.0,@aws-cdk/cx-api=1.3.0,@aws-cdk/region-info=1.3.0,jsii-runtime=node.js/v10.15.3
Outputs:
  SpikeOutput:
    Value:
      Fn::Sub: https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/blah/hello

